version: "3.8"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./backend:/app
    environment:
      TZ: Asia/Tokyo
    command: npm run dev
    expose:
      - 3000
    ports:
      - 3000:3000

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      TZ: Asia/Tokyo
      discovery.type: single-node
      xpack.security.enabled: false
      # ELASTIC_PASSWORD: password
    expose:
      - 9200
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    expose:
      - 5601
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # ELASTICSEARCH_USERNAME: elastic
      # ELASTICSEARCH_PASSWORD: password

volumes:
  es-data:
  
