version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
    command: npm run dev
    expose:
      - 3000
    ports:
      - "3000:3000"
